# Site settings
title: peiwen
email: 674898224@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://troubleman.github.io" # the base hostname & protocol for your site

# 控制生成的文章url
permalink: /:year/:month/:day/:title.html

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'


# Social account
# twitter:  username
weibo:    2458688147
github:   troubleman
# codepen:  username
# dribbble: username


# Comment
disqus_shortname: peiwen-hao


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
highlighter: pygments

kramdown:
  input: GFM

sass:
  style: compressed

